### ISSUE TITLE
KeyError in ORF prediction

### ISSUE THREAD

**Issue by wheelern** [ConesaLab/SQANTI3#5] opened 2020-05-26 16:32 UTC
I'm getting a KeyError during the classification step:

```
**** Performing Classification of Isoforms....
Traceback (most recent call last):
  File "/home/BIOTECH/zamanian/install/SQANTI3/sqanti3_qc.py", line 2268, in <module>
    main()
  File "/home/BIOTECH/zamanian/install/SQANTI3/sqanti3_qc.py", line 2261, in main
    run(args)
  File "/home/BIOTECH/zamanian/install/SQANTI3/sqanti3_qc.py", line 1710, in run
    isoforms_info = isoformClassification(args, isoforms_by_chr, refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene, genome_dict, indelsJunc, orfDict)
  File "/home/BIOTECH/zamanian/install/SQANTI3/sqanti3_qc.py", line 1553, in isoformClassification
    orfDict[rec.id].cds_genomic_end   = m[orfDict[rec.id].cds_end-1] + 1    # make it 1-based
KeyError: 1034
```
Using the `--skipORF` option allows the classification step to complete.

**Comment by Magdoll** [comment] 2020-08-05 18:27
Hi @wheelern ,
Do you still have this issue? If you still need it address, please let me know and I may need to ask for your data to confirm the error.
-Liz

**Comment by Karthickrishnan** [comment] 2020-08-20 08:05
Hi,
I too have a similar issue, however using the --skipORF option completes the run successfully. Is this normal??

**** Performing Classification of Isoforms....
Traceback (most recent call last):
  File "/home/karthic/Tools/SQANTI3/sqanti3_qc.py", line 2289, in <module>
    main()
  File "/home/karthic/Tools/SQANTI3/sqanti3_qc.py", line 2273, in main
    run(args)
  File "/home/karthic/Tools/SQANTI3/sqanti3_qc.py", line 1720, in run
    isoforms_info = isoformClassification(args, isoforms_by_chr, refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene, genome_dict, indelsJunc, orfDict)
  File "/home/karthic/Tools/SQANTI3/sqanti3_qc.py", line 1563, in isoformClassification
    orfDict[rec.id].cds_genomic_end   = m[orfDict[rec.id].cds_end-1] + 1    # make it 1-based
KeyError: 1466


Thank you,
karthic

**Comment by Magdoll** [comment] 2020-08-29 02:12
Hi @Karthickrishnan , no I think there's some bug in processing the ORF data in there. Will you be willing to share data for me to troubleshoot? 
-Liz

**Comment by ljw90607** [comment] 2020-11-18 01:48
Dear @Magdoll,

Hi I am getting the same issue mentioned above with using nanopore data and Gencode annotation gtf file. I am wondering if this issue has been fixed yet. 

Thank you very much for your help!


Jungwoo

**Comment by Magdoll** [comment] 2020-11-19 19:14
@ljw90607 ,
Hi Jungwoo, are you willing to share the data to let me test it? If so plz provide an email to request file upload.Thx!
-Liz

**Comment by ljw90607** [comment] 2020-11-20 00:20
Dear @Magdoll,

Thank you Liz for the reply. ljw90607@hotmail.com 

Jungwoo

**Comment by Magdoll** [comment] 2020-11-20 19:08
To @ljw90607 , file request sent.

**Comment by ljw90607** [comment] 2020-11-21 16:00
Dear @Magdoll.
I have sent the test data for you to check.
Currently, I have faced another error related with issue #11 
Would you please check on both errors and see what the problem might be?

Thank you for your wonderful help!

Jungwoo

**Comment by zokozen** [comment] 2020-12-16 18:09
I keep getting a keyerror 906 or AssertionError, and am unable to get a complete classification file at this time. I have attached the error below. Please advise on how I can proceed.

Thank you. 
Zenith  


**** Performing Classification of Isoforms....
Traceback (most recent call last):
  File "../sqanti3_qc.py", line 2331, in <module>
    main()
  File "../sqanti3_qc.py", line 2315, in main
    run(args)
  File "../sqanti3_qc.py", line 1760, in run
    isoforms_info = isoformClassification(args, isoforms_by_chr, refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene, genome_dict, indelsJunc, orfDict)
  File "../sqanti3_qc.py", line 1600, in isoformClassification
    isoform_hit.CDS_genomic_start = m[isoform_hit.CDS_start-1] + 1  # make it 1-based
KeyError: 906

**Comment by Magdoll** [comment] 2020-12-16 18:15
Hi @zokozen ,probably an edge case in ORF prediction. What is the full SQANTI3 command used? Can you share the iniput files as GTF?

**Comment by zokozen** [comment] 2020-12-16 18:17
This is the input command:
python ../sqanti3_qc.py Spring32.polished.hq.fasta thlaspi.filtered.gtf thlaspi.draft.04232020.fasta --force_id_ignore

Did you want me to share the gtf file here or through an email?

**Comment by Magdoll** [comment] 2020-12-16 18:27
Hi @zokozen , plz give me your email. I'll request file upload.

**Comment by zokozen** [comment] 2020-12-16 18:30
Please use this email: tandu002@umn.edu

Thanks for your quick responses.

**Comment by Magdoll** [comment] 2020-12-16 18:36
@zokozen  - request sent.

**Comment by zokozen** [comment] 2020-12-16 18:42
I'm sorry I did not receive the email. Could you please resend me the request.

**Comment by Magdoll** [comment] 2020-12-16 18:46
@zokozen  - 
The request for a Drop-off has been sent to at tandu002@umn.edu.
It is valid from 2020-12-16 10:35:10 to 2020-12-23 10:35:11.

If the recipient wants to send files to you before their request arrives, they should

Go to https://portal.pacificbiosciences.com/
Select "Drop-off Files"
Enter the request code "018 817 045"
Click on the "Next" button
You may close this window.

**Comment by zokozen** [comment] 2020-12-16 19:51
Thank you, the files have been dropped off.

**Comment by Magdoll** [comment] 2020-12-16 20:30
Hi @zokozen ,
The problem is both subtle and not so subtle.... briefly, it's because you gave SQANTI3 an input fasta in which one or more of the transcripts mapped to multiple regions - and SQANTI3 by default expects each transcript to have exactly one alignment and at most one ORF prediction. 

The solution is to basically never run SQANTI3 with input fasta (i know that was the default suggestion on the README but I've since updated it) but to give it an input GFF3/GTF that you [obtain by running Cupcake collapse](https://github.com/Magdoll/cDNA_Cupcake/wiki/Cupcake:-supporting-scripts-for-Iso-Seq-after-clustering-step#collapse)

The commands have successfully run:

```
minimap2 -ax splice -uf --secondary=no -t 30 thlaspi.draft.04232020.fasta Spring32.polished.hq.fasta > Spring32.polished.hq.fasta.sam
sort -k 3,3 -k 4,4n Spring32.polished.hq.fasta.sam > Spring32.polished.hq.fasta.sorted.sam
collapse_isoforms_by_sam.py --input Spring32.polished.hq.fasta -s Spring32.polished.hq.fasta.sorted.sam -c 0.99 -i 0.95 -o hq.5merge
python ~/GitHub/SQANTI3/sqanti3_qc.py --gtf hq.5merge.collapsed.gff thlaspi.filtered.gtf thlaspi.draft.04232020.fasta
```

If you specifically want to look at chimerically mapped transcripts (aka potential fusions), you need to run Cupcake [fusion_finder.py](https://github.com/Magdoll/cDNA_Cupcake/wiki/Cupcake:-supporting-scripts-for-Iso-Seq-after-clustering-step#fusion) separately and run SQANTI3 on that output with `--is_fusion`, because fusions have to be treated differently in SQANTI3.

I've emailed you the result. Check your SPAM filter. The email will be coming from "Pacific Biosciences (itsupport@pacificbiosciences.com)"

**Comment by zokozen** [comment] 2020-12-16 20:53
Thank you for your comprehensive response. 

I did not receive the email with the results. I checked all related folders and spam on tandu002@umn.edu
I also not receive the initial request email, but only managed to drop off the files using your link and code. 

Please let me know if we can use the pick-up files method to exchange results, or please go ahead and resend the results to my alternate email address: zenith.tandukar@gmail.com

**Comment by Magdoll** [comment] 2020-12-16 20:55
Dropped it off to your gmail

**Comment by zokozen** [comment] 2020-12-16 21:05
Received. Thanks again. I appreciate all of your assistance and time.

**Comment by ljw90607** [comment] 2020-12-24 05:35
Dear @Magdoll,

Hi I am wondering if my test data has been checked yet.
Would the lack of collapsing step be the issue? if so, do I just need the collapsed.and the raw fastq for input?

Thank you for your help

Jungwoo

**Comment by xiaonalu** [comment] 2021-08-28 14:48
Hi, I want to run the ORF along with the --is_fusion. Where could I find or generate a ORF of mouse as input here? Thanks

Currently if --is_fusion is used, no ORFs will be predicted. Supply --orf_input if you want ORF to run!

**Comment by Magdoll** [comment] 2021-09-03 03:51
Hi @xiaonalu ,
Didn't you answer your own question with the message here?

```
Currently if --is_fusion is used, no ORFs will be predicted. Supply --orf_input if you want ORF to run!
```

It should work with `--is_fusion` if you also supply `--orf_input [fasta sequence to predict ORF from]`

**Closed** 2021-09-03 03:52 UTC
