### ISSUE TITLE
Values in ORF_length column are not the same as real length of ORF_seq

### ISSUE THREAD

**Issue by Dongxu-Zheng** [ConesaLab/SQANTI3#178] opened 2023-01-12 15:36 UTC
Hi, thanks for developing SQANTI3! I have a question maybe it is referred to #103 

I used SQANTI3 to analyze Pacbio Iso-seq data. I found that the values of ORF_length are not the same as the real length of the ORF_seq in the sqanti3 output file. I found that there is a file in .faa format and the values of ORF_length are the same as ORF_seq in this .faa file. Now I am confused about which ORF seq is the truth. If my understanding is correct, I think the ORF seq should come from this .faa file since it is the output from GeneMarkS-T. But I was wondering where the ORF_seq in SQANTI3 output file comes from. Is there anything wrong with the script?

Here is what I checked in my SQANTI3 output.
![image](https://user-images.githubusercontent.com/65728158/212109970-33283511-181c-4b0b-8e0c-b084d6a8cd67.png)

ORF_length and ORF_seq are the results from SQANTI3 output. ORF_seq_length is the exact length of ORF_seq. It is 107 instead of 88. I then added the ORF sequencing from .faa file that is totally different from ORF_seq and the length is 88, which is the same as ORF_length.

Best,
Dongxu

**Comment by almart7** [comment] 2023-01-16 10:46
Hello @Dongxu-Zheng  , we are working on your issue and will answer as soon as possible. Sorry for the inconvenience!

**Comment by Dongxu-Zheng** [comment] 2023-01-16 10:51
> Hello @Dongxu-Zheng , we are working on your issue and will answer as soon as possible. Sorry for the inconvenience!

Hi, Thanks for your reply. I wondered if you need the version of SQANTI3 I used for my analysis. I know SQANTI3 really had a great update last year. I analyzed my data in March 2022 but am not exactly sure of the version number of SQANTI3 I used at that moment. If you need any further information, please let me know! Thank you!!!

Cheers,
Dongxu

**Comment by aarzalluz** [comment] 2023-01-17 09:56
Duplicate of issue #103.

**Comment by FJPardoPalacios** [comment] 2023-01-17 17:35
Hi @Dongxu-Zheng ,

This was a bug that was fixed. `ORF_seq` column used to include the peptide sequence before the starting Methionine, but it was trimmed out when output in the .faa file. This problem was fixed in the latest versions, so please, update the code and you'll see this problem solved.

Bests,
Fran

**Closed by FJPardoPalacios** 2023-01-17 17:35 UTC
Labels: duplicate, QC
