### ISSUE TITLE
AssertionError 

### ISSUE THREAD

**Issue by mad-scientist-in-training** [ConesaLab/SQANTI3#142] opened 2022-04-28 19:04 UTC
Hello, I'm running Sqanti3 with the following code: 

![image](https://user-images.githubusercontent.com/70981989/165827091-b3de4ac3-13d4-4c84-8dd0-277274ccdf74.png)

but for some reason the program will start running but then throws the following error: 

R scripting front-end version 4.1.3 (2022-03-10)
FASTA index file /data/lakecm/STAR/genomeDir/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.fai created.
**** Parsing Isoforms....
Write arguments to /data/lakecm/SQANTI3/output/sqanti_output.params.txt...
**** Running SQANTI3...
**** Parsing provided files....
Reading genome fasta /data/lakecm/STAR/genomeDir/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta....
Skipping aligning of sequences because GTF file was provided.

Indels will be not calculated since you ran SQANTI3 without alignment step (SQANTI3 with gtf format as transcriptome input).
**** Predicting ORF sequences...
**** Parsing Reference Transcriptome....
Splice Junction Coverage files not provided.
**** TSS ratio will not be calculated since SR information was not provided
**** Performing Classification of Isoforms....
Number of classified isoforms: 30895
Traceback (most recent call last):
  File "/gpfs/gsfs8/users/lakecm/SQANTI3/sqanti3_qc.py", line 2461, in <module>
    main()
  File "/gpfs/gsfs8/users/lakecm/SQANTI3/sqanti3_qc.py", line 2444, in main
    run(args)
  File "/gpfs/gsfs8/users/lakecm/SQANTI3/sqanti3_qc.py", line 1858, in run
    write_collapsed_GFF_with_CDS(isoforms_info, corrGTF, corrGTF+'.cds.gff')
  File "/gpfs/gsfs8/users/lakecm/SQANTI3/sqanti3_qc.py", line 416, in write_collapsed_GFF_with_CDS
    for r in reader:
  File "/data/lakecm/cDNA_Cupcake/cupcake/io/GFF.py", line 419, in __next__
    return self.read()
  File "/data/lakecm/cDNA_Cupcake/cupcake/io/GFF.py", line 603, in read
    rec = gmapRecord(chr, coverage=None, identity=None, strand=strand, seqid=seqid, geneid=geneid)
  File "/data/lakecm/cDNA_Cupcake/cupcake/io/GFF.py", line 324, in __init__
    assert strand == '+' or strand == '-'
AssertionError

Please let me know what to do about this. Thanks!

**Comment by aarzalluz** [comment] 2022-04-29 17:58
Hi @mad-scientist-in-training,

I believe this is a duplicate of issues #21 and #56. As explained on those threads, in your transcriptome GTF file, the strand field (column 7) should be ' +' or ' -'. Other characters are sometimes generated by some long read processing tools, i.e. '.', but they will not be accepted by Cupcake. 

Ángeles

**Closed** 2022-05-02 09:53 UTC
Labels: duplicate

**Comment by ESWRKJ** [comment] 2023-08-18 14:06
How to solve it? I use stringtie
