### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by xiaonalu** [ConesaLab/SQANTI3#126] opened 2022-03-16 11:02 UTC
Hi, I have been using the SQANTI3 for a while, it worked smoothly, until I change my datasets to human. I keep received this IndexError: list index out of range. I was wondering if this is due to the annotation and reference not matched well? Should I only use the basic, All or CHR version of annotation? I have tried many combinations, but nothing works. Thanks

The command:
python sqanti3_qc.py /ISO/ISO-2.collapsed.fasta --fasta gencode.v38.annotation.gtf /genome/GRCh38.fa -o ISO-2 -d SQANTI3_out/ISO-2/ --fl_count /ISO/ISO-2.collapsed.abundance.txt --cage_peak refTSS_hg38.bed --polyA_motif human.polyA_motif.txt -n4 --saturation --report both 

Error trace:
**** Parsing provided files....
Reading genome fasta /genome/GRCh38.fa....
****Aligning reads with Minimap2...
**** Predicting ORF sequences...
**** Parsing Reference Transcriptome....
Splice Junction Coverage files not provided.
**** TSS ratio will not be calculated since SR information was not provided
**** Reading CAGE Peak data.
**** Parsing Isoforms....
Process Process-1:
Traceback (most recent call last):
  File "/conda_envs/SQANTI3.env/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/conda_envs/SQANTI3.env/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/SQANTI3-4.2/sqanti3_qc.py", line 1902, in run
    isoforms_info, ratio_TSS_dict = isoformClassification(args, isoforms_by_chr, refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene, genome_dict, indelsJunc, orfDict, corrGTF)
  File "/SQANTI3-4.2/sqanti3_qc.py", line 1587, in isoformClassification
    cage_peak_obj = CAGEPeak(args.cage_peak)
  File "/SQANTI3-4.2/sqanti3_qc.py", line 2170, in __init__
    self.read_bed()
  File "/SQANTI3-4.2/sqanti3_qc.py", line 2175, in read_bed
    chrom = raw[0]
IndexError: list index out of range

**Comment by FJPardoPalacios** [comment] 2022-03-23 11:43
Hi!
It seems that the problem is related with your **refTSS_hg38.bed**. Please check that the chromosome names of that file match the names in the reference genome. I mean, in both chromosomes should be called *chr1*, *chr2*, *chr3*, etc or just *1*, *2*,*3*, etc, but never mix nomenclatures.

If that was the problem, please, confirm it and close the issue.

Bests,
Fran

**Comment by aarzalluz** [comment] 2022-04-12 15:44
Closing unless OP reopens.

**Closed as completed by aarzalluz** 2022-04-12 15:44 UTC
