### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by wenmore** [ConesaLab/SQANTI3#21] opened 2020-08-04 13:51 UTC
Hello,I encountered this error, anf I installed the latest SQANTI3 and cDNA_Cupcake

**** Performing Classification of Isoforms....
Number of classified isoforms: 42820
Traceback (most recent call last):
  File "/SQANTI3/sqanti3_qc.py", line 2289, in <module>
    main()
  File "/SQANTI3/sqanti3_qc.py", line 2273, in main
    run(args)
  File "/SQANTI3/sqanti3_qc.py", line 1724, in run
    write_collapsed_GFF_with_CDS(isoforms_info, corrGTF, corrGTF+'.cds.gff')
  File "/SQANTI3/sqanti3_qc.py", line 425, in write_collapsed_GFF_with_CDS
    for r in reader:
  File "/cDNA_Cupcake/cupcake/io/GFF.py", line 408, in __next__
    return self.read()
  File "/cDNA_Cupcake/cupcake/io/GFF.py", line 579, in read
    assert raw[2] == 'transcript'
AssertionError

**Comment by Magdoll** [comment] 2020-08-05 18:26
Hi @wenmore ,
This is most likely due to GFF3/GTF formatting issues. Please see this old [SQANTI2 ticket](https://github.com/Magdoll/SQANTI2/issues/58) that solved the issue with gff format conversion.

Let us know how it goes.
Thanks
-Liz

**Comment by Magdoll** [comment] 2020-09-08 00:12
Closing unless OP opens this again.

**Closed by Magdoll** 2020-09-08 00:12 UTC

**Comment by mchimenti** [comment] 2021-04-14 16:29
I also have this problem and I am using SQANTI3, python 3 and cupcake v. 22.0.0.  The "fix" in the SQANTI2 issue did not solve the problem.  

After using gffread to convert to canonical gff3 format, my gff input looks like: 
```

1	PacBio	transcript	4115663	4409235	.	-	.	transcript_id "PB.1.1"; gene_id "PB.1";
1	PacBio	exon	4115663	4115948	.	-	.	transcript_id "PB.1.1"; gene_id "PB.1";
1	PacBio	exon	4119668	4119712	.	-	.	transcript_id "PB.1.1"; gene_id "PB.1";
1	PacBio	exon	4120015	4120073	.	-	.	transcript_id "PB.1.1"; gene_id "PB.1";
1	PacBio	exon	4142612	4142766	.	-	.	transcript_id "PB.1.1"; gene_id "PB.1";
1	PacBio	exon	4147812	4147963	.	-	.	transcript_id "PB.1.1"; gene_id "PB.1";
1	PacBio	exon	4148612	4148744	.	-	.	transcript_id "PB.1.1"; gene_id "PB.1";
1	PacBio	exon	4163855	4163941	.	-	.	transcript_id "PB.1.1"; gene_id "PB.1";
1	PacBio	exon	4170205	4170404	.	-	.	transcript_id "PB.1.1"; gene_id "PB.1";
1	PacBio	exon	4197534	4197641	.	-	.	transcript_id "PB.1.1"; gene_id "PB.1";

```
Regardless, I still get: 
```

`R scripting front-end version 3.6.1 (2019-07-05)
Error corrected FASTA /Shared/Bioinformatics/data/mchiment/cui/project_pacbio_isoseq_mar2021/SQANTI3/test_run_4/test4_corrected.fasta already exists. Using it...
WARNING: Skipping ORF prediction because user requested it. All isoforms will be non-coding!
WARNING: All input isoforms were predicted as non-coding
WARNING: ref annotation contains chromosomes not in genome: GL456211.1,CHR_MG4211_PATCH,JH584303.1,CHR_MG4248_PATCH,GL456233.1,JH584296.1,GL456350.1,GL456354.1,CHR_MG117_PATCH,JH584293.1,CHR_MG4254_PATCH,JH584295.1,JH584294.1,CHR_MG4222_MG3908_PATCH,GL456216.1,CHR_MG153_PATCH,CHR_MG3562_PATCH,GL456221.1,CHR_MG4212_PATCH,CHR_MG4261_PATCH,JH584304.1,JH584298.1,GL456210.1,CHR_MG4265_PATCH,CHR_MG4180_PATCH,CHR_MG4136_PATCH,CHR_MMCHR1_CHORI29_IDD5_1,JH584292.1,CHR_MG3829_PATCH,CHR_MG4209_PATCH,CHR_MG132_PATCH,CHR_MG3609_PATCH,CHR_MG4264_PATCH,CHR_MG4151_PATCH,CHR_MG4249_PATCH,CHR_MG3833_PATCH,CHR_MG4266_PATCH,JH584299.1,GL456219.1,CHR_MG4214_PATCH,CHR_MG3231_PATCH,CHR_MG184_PATCH,CHR_MG4255_PATCH,CHR_MG3561_PATCH,CHR_MG4213_PATCH,GL456212.1,JH584297.1

**** Parsing Isoforms....
Write arguments to /Shared/Bioinformatics/data/mchiment/cui/project_pacbio_isoseq_mar2021/SQANTI3/test_run_4/test4.params.txt...
**** Running SQANTI3...
**** Parsing provided files....
Reading genome fasta /Shared/Bioinformatics/data/mchiment/cui/project_pacbio_isoseq_mar2021/GRCm38/genome.fa....
**** Predicting ORF sequences...
**** Parsing Reference Transcriptome....
/Shared/Bioinformatics/data/mchiment/cui/project_pacbio_isoseq_mar2021/SQANTI3/test_run_4/refAnnotation_test4.genePred already exists. Using it.
Splice Junction Coverage files not provided.
**** Performing Classification of Isoforms....
Number of classified isoforms: 83097
Traceback (most recent call last):
  File "/Users/mchiment/SQANTI3/sqanti3_qc.py", line 2337, in <module>
    main()
  File "/Users/mchiment/SQANTI3/sqanti3_qc.py", line 2321, in main
    run(args)
  File "/Users/mchiment/SQANTI3/sqanti3_qc.py", line 1770, in run
    write_collapsed_GFF_with_CDS(isoforms_info, corrGTF, corrGTF+'.cds.gff')
  File "/Users/mchiment/SQANTI3/sqanti3_qc.py", line 413, in write_collapsed_GFF_with_CDS
    for r in reader:
  File "/Users/mchiment/cDNA_Cupcake/cupcake/io/GFF.py", line 408, in __next__
    return self.read()
  File "/Users/mchiment/cDNA_Cupcake/cupcake/io/GFF.py", line 579, in read
    assert raw[2] == 'transcript'
AssertionError`
```

**Comment by mchimenti** [comment] 2021-04-14 16:55
Commenting out the offending line (579) simply leads to a further assertion error downstream: 

```
Traceback (most recent call last):
  File "/Users/mchiment/SQANTI3/sqanti3_qc.py", line 2337, in <module>
    main()
  File "/Users/mchiment/SQANTI3/sqanti3_qc.py", line 2321, in main
    run(args)
  File "/Users/mchiment/SQANTI3/sqanti3_qc.py", line 1770, in run
    write_collapsed_GFF_with_CDS(isoforms_info, corrGTF, corrGTF+'.cds.gff')
  File "/Users/mchiment/SQANTI3/sqanti3_qc.py", line 413, in write_collapsed_GFF_with_CDS
    for r in reader:
  File "/Users/mchiment/cDNA_Cupcake/cupcake/io/GFF.py", line 408, in __next__
    return self.read()
  File "/Users/mchiment/cDNA_Cupcake/cupcake/io/GFF.py", line 602, in read
    rec.add_exon(s, e, s, e, rstrand='+', score=None)
  File "/Users/mchiment/cDNA_Cupcake/cupcake/io/GFF.py", line 383, in add_exon
    assert len(self.ref_exons) == 0 or self.ref_exons[-1].end <= rStart0
AssertionError
```

**Comment by ttmgr** [comment] 2021-04-20 11:22
Im experiencing the same error. Everything is up-to-date and I also tried converting it into gff3 format before running SQANTI on it but no chance.

**Comment by Magdoll** [comment] 2021-04-20 14:35
Hi @mchimenti  - can you share the input GTF/GFF3 with me? I'll need an email.

**Comment by mchimenti** [comment] 2021-04-20 16:09
Hi @Magdoll.  Thanks for re-opening this issue for us.  I've attached both the GFF output of cupcake, and the GFF3 file from your recommended conversion procedure. 

[chimenti_gff_gff3_inputs_Archive.zip](https://github.com/ConesaLab/SQANTI3/files/6345016/chimenti_gff_gff3_inputs_Archive.zip)



michael-chimenti@uiowa.edu.

**Comment by mchimenti** [comment] 2021-06-01 17:16
Hi @Magdoll, do you have an update on this issue?

**Comment by Magdoll** [comment] 2021-06-01 19:41
Hi @mchimenti i'm working on it will get back to you when i know where the issue is.

**Comment by Magdoll** [comment] 2021-06-01 19:46
It is still Genemark (GMST) that is giving everyone a bad day. I gotta think about how to address this. stay tuned.

**Comment by mchimenti** [comment] 2021-08-31 16:35
Hi @Magdoll, I updated cupcake to v26 and SQANTI3 to v4.1, but I am still having this same issue (the "AssertionError" at line 590 of GFF.py).  It really looks to me like it sees "exon" on the second line, in field 3 (python raw[2]), and fails the assertion.  Am I missing something?  

I don't see why it would matter if the final field has transcript_id or gene_id first, since the assertion is failing on the test on the third field, not the last field.  

Would really appreciate some insight on this.  I have clients who are desperate to get their Isoseq data annotated and QC'd. 

Thank you.  

***************************
class collapseGFFReader(gmapGFFReader):
    def read(self):
        """
        PacBio-style GFF from the collapsed output, which is
        0) chrmosome
        1) source (PacBio)
        2) feature (transcript|exon)
        3) start (1-based)
        4) end (1-based)
        5) score (always .)
        6) strand
        7) frame (always .)
        8) blurb

        ex:
        chr1    PacBio  transcript      897326  901092  .       +       .       gene_id "PB.1"; transcript_id "PB.1.1";
        chr1    PacBio  exon    897326  897427  .       +       .       gene_id "PB.1"; transcript_id "PB.1.1";
        """
 cur = self.f.tell()
        line = self.f.readline().strip()
        if self.f.tell() == cur:
            raise StopIteration("EOF reached!!")

        raw = line.strip().split('\t')
        assert raw[2] == 'transcript'
        chr = raw[0]
        strand = raw[6]
        seqid = None
        geneid = None
        for stuff in raw[8].split(';'):
            if len(stuff.strip()) > 0:
                a, b = stuff.strip().split()
                if a == 'transcript_id':
                    seqid = b[1:-1]
                if a == 'gene_id':
                    geneid = b[1:-1]

**Comment by hmdfirst** [comment] 2023-11-01 15:47
Hi Liz,

I am having the same issue using a file converted from TAMA. 

`
Traceback (most recent call last):
  File "./soft/SQUANTI3-52/SQANTI3-5.2/sqanti3_qc.py", line 2542, in <module>
    main()
  File "../soft/SQUANTI3-52/SQANTI3-5.2/sqanti3_qc.py", line 2525, in main
    run(args)
  File "./soft/SQUANTI3-52/SQANTI3-5.2/sqanti3_qc.py", line 1892, in run
    write_collapsed_GFF_with_CDS(isoforms_info, corrGTF, corrGTF+'.cds.gff')
  File "./soft/SQUANTI3-52/SQANTI3-5.2/sqanti3_qc.py", line 420, in write_collapsed_GFF_with_CDS
    for r in reader:
  File "./soft/cDNA_Cupcake/cupcake/io/GFF.py", line 408, in __next__
    return self.read()
  File "./soft/cDNA_Cupcake/cupcake/io/GFF.py", line 586, in read
    assert raw[2] == 'transcript'
AssertionError
`

The file was converted using tama_convert_bed_gtf_ensembl_no_cds.py and I checked for strands in column 7 and all looks good. here is the head of the gff file:

`
chr1	PBRI	gene	14363	29359	.	-	.	gene_id "G1";
chr1	PBRI	transcript	14363	29345	.	-	.	gene_id "G1"; transcript_id "G1.1"; uniq_trans_id "G1.1";
chr1	PBRI	exon	14363	16765	.	-	.	gene_id "G1"; transcript_id "G1.1"; exon_number "5"; uniq_trans_id "G1.1";
chr1	PBRI	exon	16858	17055	.	-	.	gene_id "G1"; transcript_id "G1.1"; exon_number "4"; uniq_trans_id "G1.1";
chr1	PBRI	exon	17233	17742	.	-	.	gene_id "G1"; transcript_id "G1.1"; exon_number "3"; uniq_trans_id "G1.1";
chr1	PBRI	exon	17915	24891	.	-	.	gene_id "G1"; transcript_id "G1.1"; exon_number "2"; uniq_trans_id "G1.1";
chr1	PBRI	exon	29321	29345	.	-	.	gene_id "G1"; transcript_id "G1.1"; exon_number "1"; uniq_trans_id "G1.1";
chr1	PBRI	transcript	14402	29359	.	-	.	gene_id "G1"; transcript_id "G1.2"; uniq_trans_id "G1.2";
chr1	PBRI	exon	14402	14829	.	-	.	gene_id "G1"; transcript_id "G1.2"; exon_number "12"; uniq_trans_id "G1.2";
chr1	PBRI	exon	14970	15038	.	-	.	gene_id "G1"; transcript_id "G1.2"; exon_number "11"; uniq_trans_id "G1.2";
chr1	PBRI	exon	15796	15947	.	-	.	gene_id "G1"; transcript_id "G1.2"; exon_number "10"; uniq_trans_id "G1.2";
chr1	PBRI	exon	16607	16765	.	-	.	gene_id "G1"; transcript_id "G1.2"; exon_number "9"; uniq_trans_id "G1.2";
chr1	PBRI	exon	16858	17055	.	-	.	gene_id "G1"; transcript_id "G1.2"; exon_number "8"; uniq_trans_id "G1.2";
chr1	PBRI	exon	17233	17368	.	-	.	gene_id "G1"; transcript_id "G1.2"; exon_number "7"; uniq_trans_id "G1.2";
chr1	PBRI	exon	17606	17742	.	-	.	gene_id "G1"; transcript_id "G1.2"; exon_number "6"; uniq_trans_id "G1.2";
chr1	PBRI	exon	17915	18061	.	-	.	gene_id "G1"; transcript_id "G1.2"; exon_number "5"; uniq_trans_id "G1.2";
chr1	PBRI	exon	18268	18369	.	-	.	gene_id "G1"; transcript_id "G1.2"; exon_number "4"; uniq_trans_id "G1.2";
chr1	PBRI	exon	18501	18554	.	-	.	gene_id "G1"; transcript_id "G1.2"; exon_number "3"; uniq_trans_id "G1.2";
chr1	PBRI	exon	18913	24891	.	-	.	gene_id "G1"; transcript_id "G1.2"; exon_number "2"; uniq_trans_id "G1.2";
chr1	PBRI	exon	29321	29359	.	-	.	gene_id "G1"; transcript_id "G1.2"; exon_number "1"; uniq_trans_id "G1.2";
chr1	PBRI	transcript	14407	21166	.	-	.	gene_id "G1"; transcript_id "G1.3"; uniq_trans_id "G1.3";
chr1	PBRI	exon	14407	14829	.	-	.	gene_id "G1"; transcript_id "G1.3"; exon_number "8"; uniq_trans_id "G1.3";
chr1	PBRI	exon	14970	15038	.	-	.	gene_id "G1"; transcript_id "G1.3"; exon_number "7"; uniq_trans_id "G1.3";
chr1	PBRI	exon	15796	16765	.	-	.	gene_id "G1"; transcript_id "G1.3"; exon_number "6"; uniq_trans_id "G1.3";
chr1	PBRI	exon	16858	17055	.	-	.	gene_id "G1"; transcript_id "G1.3"; exon_number "5"; uniq_trans_id "G1.3";
chr1	PBRI	exon	17233	17368	.	-	.	gene_id "G1"; transcript_id "G1.3"; exon_number "4"; uniq_trans_id "G1.3";
chr1	PBRI	exon	17606	17742	.	-	.	gene_id "G1"; transcript_id "G1.3"; exon_number "3"; uniq_trans_id "G1.3";
chr1	PBRI	exon	17915	18061	.	-	.	gene_id "G1"; transcript_id "G1.3"; exon_number "2"; uniq_trans_id "G1.3";
chr1	PBRI	exon	18268	21166	.	-	.	gene_id "G1"; transcript_id "G1.3"; exon_number "1"; uniq_trans_id "G1.3";
chr1	PBRI	transcript	14407	29345	.	-	.	gene_id "G1"; transcript_id "G1.4"; uniq_trans_id "G1.4";
chr1	PBRI	exon	14407	14829	.	-	.	gene_id "G1"; transcript_id "G1.4"; exon_number "4"; uniq_trans_id "G1.4";
chr1	PBRI	exon	14970	17742	.	-	.	gene_id "G1"; transcript_id "G1.4"; exon_number "3"; uniq_trans_id "G1.4";
chr1	PBRI	exon	17915	24891	.	-	.	gene_id "G1"; transcript_id "G1.4"; exon_number "2"; uniq_trans_id "G1.4";
chr1	PBRI	exon	29321	29345	.	-	.	gene_id "G1"; transcript_id "G1.4"; exon_number "1"; uniq_trans_id "G1.4";
chr1	PBRI	transcript	14407	29353	.	-	.	gene_id "G1"; transcript_id "G1.5"; uniq_trans_id "G1.5";
chr1	PBRI	exon	14407	14829	.	-	.	gene_id "G1"; transcript_id "G1.5"; exon_number "9"; uniq_trans_id "G1.5";
chr1	PBRI	exon	14970	15038	.	-	.	gene_id "G1"; transcript_id "G1.5"; exon_number "8"; uniq_trans_id "G1.5";
chr1	PBRI	exon	15796	16765	.	-	.	gene_id "G1"; transcript_id "G1.5"; exon_number "7"; uniq_trans_id "G1.5";
chr1	PBRI	exon	16858	17055	.	-	.	gene_id "G1"; transcript_id "G1.5"; exon_number "6"; uniq_trans_id "G1.5";
chr1	PBRI	exon	17233	17742	.	-	.	gene_id "G1"; transcript_id "G1.5"; exon_number "5"; uniq_trans_id "G1.5";
chr1	PBRI	exon	17915	18061	.	-	.	gene_id "G1"; transcript_id "G1.5"; exon_number "4"; uniq_trans_id "G1.5";
chr1	PBRI	exon	18268	18366	.	-	.	gene_id "G1"; transcript_id "G1.5"; exon_number "3"; uniq_trans_id "G1.5";
chr1	PBRI	exon	24738	24891	.	-	.	gene_id "G1"; transcript_id "G1.5"; exon_number "2"; uniq_trans_id "G1.5";
chr1	PBRI	exon	29321	29353	.	-	.	gene_id "G1"; transcript_id "G1.5"; exon_number "1"; uniq_trans_id "G1.5";
chr1	PBRI	transcript	14407	29356	.	-	.	gene_id "G1"; transcript_id "G1.6"; uniq_trans_id "G1.6";
chr1	PBRI	exon	14407	14829	.	-	.	gene_id "G1"; transcript_id "G1.6"; exon_number "10"; uniq_trans_id "G1.6";
chr1	PBRI	exon	14970	15038	.	-	.	gene_id "G1"; transcript_id "G1.6"; exon_number "9"; uniq_trans_id "G1.6";
chr1	PBRI	exon	15796	15947	.	-	.	gene_id "G1"; transcript_id "G1.6"; exon_number "8"; uniq_trans_id "G1.6";
chr1	PBRI	exon	16607	16765	.	-	.	gene_id "G1"; transcript_id "G1.6"; exon_number "7"; uniq_trans_id "G1.6";
chr1	PBRI	exon	16858	17055	.	-	.	gene_id "G1"; transcript_id "G1.6"; exon_number "6"; uniq_trans_id "G1.6";
chr1	PBRI	exon	17233	17368	.	-	.	gene_id "G1"; transcript_id "G1.6"; exon_number "5"; uniq_trans_id "G1.6";
chr1	PBRI	exon	17606	17742	.	-	.	gene_id "G1"; transcript_id "G1.6"; exon_number "4"; uniq_trans_id "G1.6";
chr1	PBRI	exon	17915	18061	.	-	.	gene_id "G1"; transcript_id "G1.6"; exon_number "3"; uniq_trans_id "G1.6";
chr1	PBRI	exon	18268	24891	.	-	.	gene_id "G1"; transcript_id "G1.6"; exon_number "2"; uniq_trans_id "G1.6";
chr1	PBRI	exon	29321	29356	.	-	.	gene_id "G1"; transcript_id "G1.6"; exon_number "1"; uniq_trans_id "G1.6";
chr1	PBRI	transcript	14409	29345	.	-	.	gene_id "G1"; transcript_id "G1.7"; uniq_trans_id "G1.7";
chr1	PBRI	exon	14409	14829	.	-	.	gene_id "G1"; transcript_id "G1.7"; exon_number "9"; uniq_trans_id "G1.7";
chr1	PBRI	exon	14970	15038	.	-	.	gene_id "G1"; transcript_id "G1.7"; exon_number "8"; uniq_trans_id "G1.7";
chr1	PBRI	exon	15796	15947	.	-	.	gene_id "G1"; transcript_id "G1.7"; exon_number "7"; uniq_trans_id "G1.7";
chr1	PBRI	exon	16607	16765	.	-	.	gene_id "G1"; transcript_id "G1.7"; exon_number "6"; uniq_trans_id "G1.7";
chr1	PBRI	exon	16858	17055	.	-	.	gene_id "G1"; transcript_id "G1.7"; exon_number "5"; uniq_trans_id "G1.7";
chr1	PBRI	exon	17233	17368	.	-	.	gene_id "G1"; transcript_id "G1.7"; exon_number "4"; uniq_trans_id "G1.7";
chr1	PBRI	exon	17606	17742	.	-	.	gene_id "G1"; transcript_id "G1.7"; exon_number "3"; uniq_trans_id "G1.7";
chr1	PBRI	exon	17915	24891	.	-	.	gene_id "G1"; transcript_id "G1.7"; exon_number "2"; uniq_trans_id "G1.7";
chr1	PBRI	exon	29321	29345	.	-	.	gene_id "G1"; transcript_id "G1.7"; exon_number "1"; uniq_trans_id "G1.7";
chr1	PBRI	transcript	14409	29347	.	-	.	gene_id "G1"; transcript_id "G1.8"; uniq_trans_id "G1.8";
chr1	PBRI	exon	14409	14829	.	-	.	gene_id "G1"; transcript_id "G1.8"; exon_number "8"; uniq_trans_id "G1.8";
chr1	PBRI	exon	14970	16765	.	-	.	gene_id "G1"; transcript_id "G1.8"; exon_number "7"; uniq_trans_id "G1.8";
chr1	PBRI	exon	16858	17055	.	-	.	gene_id "G1"; transcript_id "G1.8"; exon_number "6"; uniq_trans_id "G1.8";
chr1	PBRI	exon	17233	17742	.	-	.	gene_id "G1"; transcript_id "G1.8"; exon_number "5"; uniq_trans_id "G1.8";
chr1	PBRI	exon	17915	18061	.	-	.	gene_id "G1"; transcript_id "G1.8"; exon_number "4"; uniq_trans_id "G1.8";
chr1	PBRI	exon	18268	18366	.	-	.	gene_id "G1"; transcript_id "G1.8"; exon_number "3"; uniq_trans_id "G1.8";
chr1	PBRI	exon	24738	24891	.	-	.	gene_id "G1"; transcript_id "G1.8"; exon_number "2"; uniq_trans_id "G1.8";
chr1	PBRI	exon	29321	29347	.	-	.	gene_id "G1"; transcript_id "G1.8"; exon_number "1"; uniq_trans_id "G1.8";
chr1	PBRI	transcript	14409	29359	.	-	.	gene_id "G1"; transcript_id "G1.9"; uniq_trans_id "G1.9";
chr1	PBRI	exon	14409	14829	.	-	.	gene_id "G1"; transcript_id "G1.9"; exon_number "10"; uniq_trans_id "G1.9";
chr1	PBRI	exon	14970	15038	.	-	.	gene_id "G1"; transcript_id "G1.9"; exon_number "9"; uniq_trans_id "G1.9";
chr1	PBRI	exon	15796	15947	.	-	.	gene_id "G1"; transcript_id "G1.9"; exon_number "8"; uniq_trans_id "G1.9";
chr1	PBRI	exon	16607	16765	.	-	.	gene_id "G1"; transcript_id "G1.9"; exon_number "7"; uniq_trans_id "G1.9";
chr1	PBRI	exon	16858	17055	.	-	.	gene_id "G1"; transcript_id "G1.9"; exon_number "6"; uniq_trans_id "G1.9";
chr1	PBRI	exon	17233	17368	.	-	.	gene_id "G1"; transcript_id "G1.9"; exon_number "5"; uniq_trans_id "G1.9";
chr1	PBRI	exon	17606	17697	.	-	.	gene_id "G1"; transcript_id "G1.9"; exon_number "4"; uniq_trans_id "G1.9";
chr1	PBRI	exon	19966	20048	.	-	.	gene_id "G1"; transcript_id "G1.9"; exon_number "3"; uniq_trans_id "G1.9";
chr1	PBRI	exon	20364	24891	.	-	.	gene_id "G1"; transcript_id "G1.9"; exon_number "2"; uniq_trans_id "G1.9";
chr1	PBRI	exon	29321	29359	.	-	.	gene_id "G1"; transcript_id "G1.9"; exon_number "1"; uniq_trans_id "G1.9";
`

I am also using the current cDNA_cupcake. I also used gffread to convert to gff and even removingthe gene track, replacing the transcrip_id and gene_id, did not help.

tracing the error in the GFF.py shows what @mchimenti reported about the exon in 3rd column. I even tried --skipORF and comented out the assertion line but the same. I would really apparaciate if you can help since it is holding a project wile the deadline is approaching. Thanks ina dvance.

**Comment by mechealeth** [comment] 2024-03-21 00:56
> It is still Genemark (GMST) that is giving everyone a bad day. I gotta think about how to address this. stay tuned.

Hi Magdoll, I  already transformed  the gtf format but still have the same error, I would like to know how to solve GMST problem.
