### ISSUE TITLE
Error processing transcripts with unassigned strands (StringTie GFF)

### ISSUE THREAD

**Issue by umranyaman** [ConesaLab/SQANTI3#96] opened 2021-11-16 16:45 UTC
Hello,

I am quite new to long-read analysis and I have been trying to analyze Nanopore long-read data for some time with Sqanti3, using gff files from Stringtie. This is to compare the annotations from Stringtie vs Sqanti3. 

I have str_merged.gff files from Stringtie (https://github.com/nanoporetech/pipeline-nanopore-ref-isoforms), and each strand is specified with + and -, when I open my gff files with rtracklayer::import function in R, so there should not be any problem with strands. What should I do?

<img width="1156" alt="Screenshot 2021-11-16 at 16 14 26" src="https://user-images.githubusercontent.com/72675757/142022945-a1f28eee-03e9-4eb6-8bad-4a05f104b8a0.png">

My gff file from Stringtie in R: 
<img width="1323" alt="Screenshot 2021-11-16 at 16 40 49" src="https://user-images.githubusercontent.com/72675757/142065088-db86e00a-24cf-4f23-a21c-37318fd0b37f.png">

The corrected gff file using above in Sqanti3 in R:
<img width="857" alt="Screenshot 2021-11-16 at 16 41 10" src="https://user-images.githubusercontent.com/72675757/142027692-67b248c7-26f3-4eb7-aca6-38ac50cd3d28.png">

Thanks very much,
Umran

**Comment by FJPardoPalacios** [comment] 2021-11-16 17:05
Hi Umran, 

I'll bet that the issue is still related with the strand... Please, check if any of your transcripts or exons present in the strand field a `.` instead of a `+` or  `-` symbol. For doing that you just have to run this command in your terminal:

`cut -f7 your_input_GFF.gff | sort | uniq -c`

You will get how many features are associated with the `+` , `-` and `.` (=unassigned) strand. SQANTI3 cannot deal with "unassigned" strands (check #62). This seems to be kind of frequent when using StringTie...

Bests,
Fran

**Comment by umranyaman** [comment] 2021-11-16 20:59
Thanks very much!

I have removed those with "." .

I have installed all the required R libraries, but not the "plotly" however I tried with many ways.. Do you have any suggestion? R version 3.6.1. 

<img width="1438" alt="Screenshot 2021-11-16 at 20 56 57" src="https://user-images.githubusercontent.com/72675757/142064446-4d002d8a-9f66-4bdd-a3da-5565b25e12d6.png">


Best,
Umran

**Comment by FJPardoPalacios** [comment] 2021-11-18 13:27
Load your `SQANTI3.env` conda environment and run this command to update the environment:

`conda env update --file SQANTI3.conda_env.yml --prune`

But first of all, remember to pull the last version of SQANTI3 repository (which includes the updated YML file)

**Comment by aarzalluz** [comment] 2022-03-31 13:12
Closing unless OP updates.

**Closed by aarzalluz** 2022-03-31 13:12 UTC
