### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by ttmgr** [ConesaLab/SQANTI3#56] opened 2021-04-20 12:42 UTC
Hi everyone,

I am trying to run SQANTI3 on a transcriptome assembled by StringTie, however I always receive the following error message: 

Traceback (most recent call last):
  File "sqanti3_qc.py", line 2334, in <module>
    main()
  File "sqanti3_qc.py", line 2318, in main
    run(args)
  File "sqanti3_qc.py", line 1767, in run
    write_collapsed_GFF_with_CDS(isoforms_info, corrGTF, corrGTF+'.cds.gff')
  File "sqanti3_qc.py", line 411, in write_collapsed_GFF_with_CDS
    for r in reader:
  File "/gcm-lfs1/tim/PaperRevisionData/SQANTI3/cDNA_Cupcake/cupcake/io/GFF.py", line 408, in __next__
    return self.read()
  File "/gcm-lfs1/tim/PaperRevisionData/SQANTI3/cDNA_Cupcake/cupcake/io/GFF.py", line 592, in read
    rec = gmapRecord(chr, coverage=None, identity=None, strand=strand, seqid=seqid, geneid=geneid)
  File "/gcm-lfs1/tim/PaperRevisionData/SQANTI3/cDNA_Cupcake/cupcake/io/GFF.py", line 324, in __init__
    assert strand == '+' or strand == '-' 

In contrast to the stringtie assemblies, sqanti3 works perfectly with Flames, Flair and PacBio assemblies.

I use the most recent version of conda, sqanti3, cdnacupcake, and genepred but its still not working. 

Does anyone have an idea how to fix this?

**Comment by aarzalluz** [comment] 2021-04-20 12:57
This may be a duplicate of #21.

**Comment by Magdoll** [comment] 2021-04-20 14:35
Hi @ttmgr it's probably a GFF3 format issue. Can you share the input with me? I'll need an email

**Comment by ttmgr** [comment] 2021-04-20 14:45
Hello there, 

Thanks for your mail. 

Sure. I will send it to you as soon as possible, either this evening or tomorrow.

The initial input was a gtf. Is this fine as well or should I sent you then the gff3 after I converted it? 

Best regards 
Tim 

Tim Reska 
+491512930711
***@***.***LMU.de

**Comment by Magdoll** [comment] 2021-05-27 14:15
Hi @ttmgr 

I figured it out. You are missing the strand field in the GFF format.
All your GFFs have a "." in the strand column (column 7), and it needs to be specific as + or - strand.

-Liz

**Closed by Magdoll** 2021-05-27 14:15 UTC
